# Generated by Django 2.2.4 on 2019-12-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecompiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='user',
        ),
    ]
