# Generated by Django 2.2.4 on 2019-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompiler', '0002_remove_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='code',
            name='source',
            field=models.CharField(default='', max_length=5000000),
        ),
        migrations.AddField(
            model_name='code',
            name='verdict',
            field=models.IntegerField(default=0),
        ),
    ]
